groups:
  - name: all
    jobs:
      - '*'
  - name: build
    jobs:
      - build*
  - name: database
    jobs:
      - update-*-database
  - name: release
    jobs:
      - 'release-*'

resource_types:
  - name: discord-alert
    type: registry-image
    source:
      repository: ghcr.io/tklein1801/concourse-discord-alert-resource
  
  - name: cogito
    type: registry-image
    check_every: 24h
    source:
      repository: pix4d/cogito

resources:
  - name: notification
    type: discord-alert
    icon: bell-ring
    source:
      url: ((discord_webhook))

  - name: node-image
    type: registry-image
    icon: nodejs
    source:
      repository: node
      tag: 22

  - name: repository
    type: git
    icon: git
    source:
      uri: git@github.com:((repo_owner))/((repo_name)).git
      private_key: ((repo_private_key))
      branch: main
      paths: [((repo_path))/**]
      ignore_paths: [((repo_path))/drizzle/**]

  - name: repository-migrations
    type: git
    icon: git
    source:
      uri: git@github.com:((repo_owner))/((repo_name)).git
      private_key: ((repo_private_key))
      branch: main
      paths: [((repo_path))/drizzle/**]

  - name: status
    type: cogito
    icon: github
    source:
      owner: ((repo_owner))
      repo: ((repo_name))
      access_token: ((github_pat))

  - name: version
    type: semver
    icon: tag-outline
    source:
      driver: s3
      initial_version: 0.0.0-rc.0
      bucket: ((version_bucket))
      key: ((service))/version
      region_name: ((version_bucket_region))
      access_key_id: ((version_bucket_access_key))
      secret_access_key: ((version_bucket_secret))

  - name: db-bucket
    type: s3
    icon: database-import
    source:
      bucket: ((db_backup_bucket))
      region_name: ((version_bucket_region))
      access_key_id: ((version_bucket_access_key))
      secret_access_key: ((version_bucket_secret))
      regexp: backup_(.*).dump

  - name: daily-timer
    type: time
    icon: clock
    source:
      interval: 24h

meta:
  gh-status-handlers: &gh-status-handlers
    on_success:
      put: status
      inputs: [repository]
      no_get: true
      params: {state: success}
    on_failure:
      put: status
      inputs: [repository]
      no_get: true
      params: {state: failure}
    on_error:
      put: status
      inputs: [repository]
      no_get: true
      params: {state: error}
    on_abort:
      put: status
      inputs: [repository]
      no_get: true
      params: {state: abort}

task-config: &task-release
  platform: linux
  inputs:
    - name: repository
    - name: version
  outputs:
    - name: repository
  params:
    CI: 'true'
    FORCE_COLOR: 1
    TURBO_TELEMETRY_DISABLED: 1
  run:
    path: sh
    args:
      - -evc
      - |
        git config --global user.name 'Thorben Klein'
        git config --global user.email thorben@tklein.it
        NEW_VERSION="$(cat version/version)"
        cd repository/((repo_path))
        npm install
        npm run test
        npm run build
        npm version "$NEW_VERSION" --no-git-tag-version
        git add package*.json
        git add ../../package*.json
        git commit -m "chore(release): Release ((service_name))-v$NEW_VERSION"
        git tag | xargs git tag -d > /dev/null
        git tag -a "((service_name))-v$NEW_VERSION" -m "Release ((service_name))-v$NEW_VERSION" > /dev/null
        echo "//registry.npmjs.org/:_authToken=((npm_token))" > ~/.npmrc
        npm publish --access public

jobs:
  - name: build-((service_name))
    public: true
    <<: *gh-status-handlers
    plan:
      - in_parallel:
          - get: node-image
          - get: repository
            trigger: true
          - get: version
            params: { pre: rc }
      - put: status
        inputs: [repository]
        params: {state: pending}
        no_get: true
      - task: build
        image: node-image
        config:
          inputs:
            - name: repository
            - name: version
          params:
            CI: 'true'
            FORCE_COLOR: 1
            TURBO_TELEMETRY_DISABLED: 1
          platform: linux
          run:
            path: sh
            args:
              - -exc
              - |
                NEW_VERSION=$(cat version/version)
                cd repository
                npm install
                npm test -- -F=@budgetbuddyde/((service_name))
                npm run build -- -F=@budgetbuddyde/((service_name))
                cd ((repo_path))
                npm version "$NEW_VERSION" --no-git-tag-version
                npm publish --access public --dry-run
      - put: version
        params: { file: version/version }

  - name: database-backup
    public: false
    on_failure:
      put: notification
      params:
        alert_type: failed
        message: 'Failed to backup database'
        role: '1342563020215291936'
    plan:
      - get: daily-timer
        trigger: true
      - task: dump-database
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: postgres
              tag: 17
          outputs:
            - name: backup
          params:
            CI: 'true'
            FORCE_COLOR: 1
            DATABASE_URL: ((database_url))
          run:
            path: sh
            args:
              - -ec
              - |
                TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
                FILE="backup_${TIMESTAMP}.dump"
                echo "Creating PostgreSQL dump..."
                pg_dump "$DATABASE_URL" -Fc -f backup/$FILE >> /dev/null
                echo "Backup created!"
      - put: db-bucket
        params:
          file: backup/*.dump

  - name: update-test-database
    public: false
    on_failure:
      put: notification
      params:
        alert_type: failed
        message: 'Failed to update test database'
        role: '1342563020215291936'
    plan:
      - in_parallel:
          - get: node-image
          - get: repository
            resource: repository-migrations
            trigger: true
      - task: apply-migrations
        image: node-image
        config:
          platform: linux
          inputs:
            - name: repository
          params:
            CI: 'true'
            FORCE_COLOR: 1
            DATABASE_URL: ((test_database_url))
          run:
            path: sh
            args:
              - -exc
              - |
                cd repository/((repo_path))
                npx drizzle-kit check
                npm run db:migrate

  - name: update-prod-database
    public: false
    on_failure:
      put: notification
      params:
        alert_type: failed
        message: 'Failed to update prod database'
        role: '1342563020215291936'
    plan:
      - in_parallel:
          - get: node-image
          - get: repository
            resource: repository-migrations
            passed: [update-test-database]
      - task: apply-migrations
        image: node-image
        config:
          platform: linux
          inputs:
            - name: repository
          params:
            CI: 'true'
            FORCE_COLOR: 1
            DATABASE_URL: ((database_url))
          run:
            path: sh
            args:
              - -exc
              - |
                cd repository/((repo_path))
                npx drizzle-kit check
                npm run db:migrate

  - name: release-patch
    on_failure:
      put: notification
      params:
        alert_type: failed
        message: 'Release of patch for ((service_name)) failed'
        role: '1342563020215291936'
    plan:
      - in_parallel:
          - get: version
            passed: [build-((service_name))]
            params: { bump: patch }
          - get: repository
          - get: node-image
      - task: build
        image: node-image
        config:
          <<: *task-release
      - put: version
        params: { file: version/version }
      - put: repository
        params:
          repository: repository
          rebase: true

  - name: release-minor
    on_failure:
      put: notification
      params:
        alert_type: failed
        message: 'Release of minor for ((service_name)) failed'
        role: '1342563020215291936'
    plan:
      - in_parallel:
          - get: version
            passed: [build-((service_name))]
            params: { bump: minor }
          - get: repository
          - get: node-image
      - task: build
        image: node-image
        config:
          <<: *task-release
      - put: version
        params: { file: version/version }
      - put: repository
        params:
          repository: repository
          rebase: true

  - name: release-major
    on_failure:
      put: notification
      params:
        alert_type: failed
        message: 'Release of major for ((service_name)) failed'
        role: '1342563020215291936'
    plan:
      - in_parallel:
          - get: version
            passed: [build-((service_name))]
            params: { bump: major }
          - get: repository
          - get: node-image
      - task: build
        image: node-image
        config:
          <<: *task-release
      - put: version
        params: { file: version/version }
      - put: repository
        params:
          repository: repository
          rebase: true
