resource_types:
  - name: discord-alert
    type: registry-image
    source:
      repository: ghcr.io/tklein1801/concourse-discord-alert-resource

resources:
  - name: notify
    type: discord-alert
    source:
      url: ((discord_webhook))

  - name: repo
    type: git
    icon: github
    source:
      uri: ((repo_uri))
      private_key: ((repo_private_key))
      branch: main
      paths: [((repo_path))/**]
      depth: 1

  - name: container-registry
    type: docker-image
    icon: docker
    source:
      repository: ((docker_image))
      username: ((docker_username))
      password: ((docker_password))

jobs:
  - name: build-and-test
    public: true
    serial: true
    on_failure:
      put: notify
      params:
        alert_type: failed
        message: 'Build of base-image failed'
        role: '1342563020215291936'
    on_success:
      put: notify
      params:
        alert_type: success
        message: 'Build and test of base-image succeeded 🎉'
        role: '1342563020215291936'
    plan:
      - get: repo
        trigger: true
      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          inputs:
            - name: repo
          outputs:
            - name: image
          params:
            CONTEXT: repo/((repo_path))
            UNPACK_ROOTFS: true
          run:
            path: build
      - task: test-image
        image: image
        config:
          platform: linux
          run:
            path: pnpm
            args: ['--version']
      - put: container-registry
        get_params: { skip_download: true }
        params:
          import_file: image/image.tar
          tag_as_latest: true
