groups:
  - name: all
    jobs:
      - '*'
  - name: build
    jobs:
      - build*
  - name: release
    jobs:
      - 'release-*'

resource_types:
  - name: discord-alert
    type: registry-image
    source:
      repository: ghcr.io/tklein1801/concourse-discord-alert-resource

  - name: cogito
    type: registry-image
    check_every: 24h
    source:
      repository: pix4d/cogito

resources:
  - name: notification
    type: discord-alert
    icon: bell-ring
    source:
      url: ((discord_webhook))

  - name: node-image
    type: registry-image
    icon: nodejs
    source:
      repository: node
      tag: 22

  - name: repository
    type: git
    icon: git
    source:
      uri: git@github.com:((repo_owner))/((repo_name)).git
      private_key: ((repo_private_key))
      branch: ((repo_branch))
      paths: [((repo_path))/**]

  - name: status
    type: cogito
    icon: github
    check_every: never
    source:
      owner: ((repo_owner))
      repo: ((repo_name))
      access_token: ((github_pat))

  - name: version
    type: semver
    icon: tag-outline
    source:
      driver: s3
      initial_version: 3.0.0-rc.0
      bucket: ((version_bucket))
      key: ((service))/version
      region_name: ((version_bucket_region))
      access_key_id: ((version_bucket_access_key))
      secret_access_key: ((version_bucket_secret))

  - name: version-prod
    type: semver
    icon: tag-outline
    source:
      driver: s3
      initial_version: 3.0.0-rc.0
      bucket: ((version_bucket))
      key: ((service))/prod
      region_name: ((version_bucket_region))
      access_key_id: ((version_bucket_access_key))
      secret_access_key: ((version_bucket_secret))

meta:
  gh-status-handlers: &gh-status-handlers
    on_success:
      put: status
      inputs: [repository]
      no_get: true
      params: {state: success}
    on_failure:
      put: status
      inputs: [repository]
      no_get: true
      params: {state: failure}
    on_error:
      put: status
      inputs: [repository]
      no_get: true
      params: {state: error}
    on_abort:
      put: status
      inputs: [repository]
      no_get: true
      params: {state: abort}

task-config: &task-release
  platform: linux
  params:
    CI: 'true'
    FORCE_COLOR: 1
    TURBO_TELEMETRY_DISABLED: 1
  inputs:
    - name: repository
    - name: version
  outputs:
    - name: repository
  run:
    path: sh
    args:
      - -evc
      - |
        NEW_VERSION=$(cat version/version)
        cd repository/((repo_path))
        git config --global user.name "Thorben Klein"
        git config --global user.email "thorben@tklein.it"
        npm version "$NEW_VERSION" --no-git-tag-version
        git add package*.json
        git add ../../package*.json
        git commit -m "chore(release): Release ((service_name))-v$NEW_VERSION"
        git tag | xargs git tag -d > /dev/null
        git tag -a "((service_name))-v$NEW_VERSION" -m "Release ((service_name))-v$NEW_VERSION" > /dev/null

jobs:
  - name: build-((service_name))
    public: true
    <<: *gh-status-handlers
    plan:
      - in_parallel:
          - get: node-image
          - get: repository
            trigger: true
          - get: version
            params: { pre: rc }
          - get: container-version
            resource: version
            params: { bump: final }
      - put: status
        inputs: [repository]
        params: {state: pending}
        no_get: true
      - task: build
        image: node-image
        config:
          platform: linux
          inputs:
            - name: repository
            - name: version
          params:
            CI: 'true'
            FORCE_COLOR: 1
            TURBO_TELEMETRY_DISABLED: 1
          run:
            path: sh
            args:
              - -exc
              - |
                NEW_VERSION=$(cat version/version)
                cd repository
                npm install
                npm run check -- -F=@budgetbuddyde/((service_name))
                #npm test -- -F=@budgetbuddyde/((service_name))
                npm run build -- -F=@budgetbuddyde/((service_name))
                cd ((repo_path))
                npm version "$NEW_VERSION" --no-git-tag-version
      - put: version
        params: { file: version/version }

  - name: release-patch
    on_failure:
      put: notification
      params:
        alert_type: failed
        message: 'Release of patch for ((service_name)) failed'
        role: '1342563020215291936'
    plan:
      - in_parallel:
          - get: node-image
          - get: repository
          - get: version
            passed: [build-((service_name))]
            params: { bump: patch }
      - task: build
        image: node-image
        config:
          <<: *task-release
      - put: version
        params: { file: version/version }
      - put: version-prod
        params: { file: version/version }
      - put: repository
        params:
          repository: repository
          rebase: true

  - name: release-minor
    on_failure:
      put: notification
      params:
        alert_type: failed
        message: 'Release of minor for ((service_name)) failed'
        role: '1342563020215291936'
    plan:
      - in_parallel:
          - get: node-image
          - get: repository
          - get: version
            passed: [build-((service_name))]
            params: { bump: minor }
      - task: build
        image: node-image
        config:
          <<: *task-release
      - put: version
        params: { file: version/version }
      - put: version-prod
        params: { file: version/version }
      - put: repository
        params:
          repository: repository
          rebase: true

  - name: release-major
    on_failure:
      put: notification
      params:
        alert_type: failed
        message: 'Release of major for ((service_name)) failed'
        role: '1342563020215291936'
    plan:
      - in_parallel:
          - get: node-image
          - get: repository
          - get: version
            passed: [build-((service_name))]
            params: { bump: major }
      - task: build
        image: node-image
        config:
          <<: *task-release
      - put: version
        params: { file: version/version }
      - put: version-prod
        params: { file: version/version }
      - put: repository
        params:
          repository: repository
          rebase: true
