[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

[[redirects]]
from = "/dashboard"
to = "/dashboard"
status = 200
force = false

[[redirects]]
from = "/transactions"
to = "/transactions"
status = 200
force = false

[[redirects]]
from = "/budget"
to = "/budget"
status = 200
force = false

[[redirects]]
from = "/subscriptions"
to = "/subscriptions"
status = 200
force = false

[[redirects]]
from = "/payment-methods"
to = "/payment-methods"
status = 200
force = false

[[redirects]]
from = "/settings"
to = "/settings"
status = 200
force = false

[[redirects]]
from = "/categories"
to = "/categories"
status = 200
force = false

[[redirects]]
from = "/sign-in"
to = "/sign-in"
status = 200
force = false

[[redirects]]
from = "/sign-up"
to = "/sign-up"
status = 200
force = false

