ARG VERSION=3.4

FROM grafana/loki:${VERSION}

# Copy the loki.yml configuration file to the container
COPY loki.yml /etc/loki/loki-config.yaml

# config.expand-env=true enables ${VAR} substitution from environment variables
CMD ["-config.file=/etc/loki/loki-config.yaml", "-config.expand-env=true"]