export const CountryMapping = new Map([
  ['DE', 'Germany'],
  ['GB', 'United Kingdom'],
  ['JP', 'Japan'],
  ['CH', 'Switzerland'],
  ['AU', 'Australia'],
  ['CA', 'Canada'],
  ['FR', 'France'],
  ['CN', 'China'],
  ['TW', 'Taiwan'],
  ['IN', 'India'],
  ['KR', 'Korea'],
  ['ES', 'Spain'],
  ['SG', 'Singapore'],
  ['SE', 'Sweden'],
  ['HK', 'Hong Kong'],
  ['NL', 'Netherlands'],
  ['IT', 'Italy'],
  ['BR', 'Brazil'],
  ['DK', 'Denmark'],
  ['ZA', 'South Africa'],
  ['FI', 'Finland'],
  ['MX', 'Mexico'],
  ['MY', 'Malaysia'],
  ['BE', 'Belgium'],
  ['NO', 'Norway'],
  ['AT', 'Austria'],
  ['PL', 'Poland'],
  ['US', 'USA'],
  ['ID', 'Indonesia'],
  ['TH', 'Thailand'],
  ['IL', 'Israel'],
  ['IE', 'Ireland'],
  ['TR', 'Turkey'],
  ['NZ', 'New Zealand'],
  ['CL', 'Chile'],
  ['PH', 'Philippines'],
  ['PT', 'Portugal'],
  ['GR', 'Greece'],
  ['HU', 'Hungary'],
  ['PE', 'Peru'],
  ['CZ', 'Czech Republic'],
  ['CO', 'Colombia'],
  ['PK', 'Pakistan'],
  ['SK', 'Slovakia'],
  ['OTHER', 'Other'],
]);

export const IndustryMapping = new Map([
  ['452020', 'Hardware Technology, Storage and Peripherals'],
  ['251020', 'Automobiles'],
  ['253010', 'Hotels, Restaurants and Leisure'],
  ['601070', 'Retail REITs'],
  ['151020', 'Building Materials'],
  ['302020', 'Food Products'],
  ['352020', 'Pharmaceuticals'],
  ['402010', 'Financial Services'],
  ['203010', 'Air Freight and Logistics'],
  ['601060', 'Residential REITs'],
  ['255030', 'General Retailers'],
  ['602010', 'Real Estate Management and Development'],
  ['201050', 'Industrial Conglomerates'],
  ['453010', 'Semiconductors and Semiconductor Equipment'],
  ['302010', 'Beverages'],
  ['601040', 'Office REITs'],
  ['601080', 'Specialized REITs'],
  ['402030', 'Capital Markets'],
  ['301010', 'Consumer Staples Distribution and Retail'],
  ['501010', 'Diversified Telecommunication Services'],
  ['255040', 'Specialty Retail'],
  ['601010', 'Diversified REITs'],
  ['601030', 'Hotel and Resort REITs'],
  ['551050', 'Independent Power and Renewable Electricity Producers'],
  ['101020', 'Oil, Gas and Consumable Fuels'],
  ['252030', 'Textiles, Apparel and Luxury Goods'],
  ['OTHER', 'Other'],
]);

export const RegionMapping = new Map([
  ['NA', 'North America'],
  ['EU', 'Europe'],
  ['AS', 'Asia'],
  ['OC', 'Oceania and Australia'],
  ['SA', 'South America'],
  ['AF', 'Africa'],
  ['ME', 'Middle East'],
  ['AN', 'Antarctica'],
  ['OTHER', 'Other'],
]);

export const SectorMapping = new Map<string, string>([
  ['sct_45', 'Information Technology'],
  ['sct_25', 'Consumer Discretionary'],
  ['sct_40', 'Financials'],
  ['sct_60', 'Real Estate'],
  ['sct_30', 'Consumer Staples'],
  ['sct_20', 'Industrials'],
  ['sct_35', 'Health Care'],
  ['sct_15', 'Materials'],
  ['sct_10', 'Energy'],
  ['sct_55', 'Utilities'],
  ['sct_50', 'Communication Services'],
  ['OTHER', 'Other'],
]);
