export const CountryMapping: Record<string, string> = {
  DE: 'Germany',
  GB: 'United Kingdom',
  JP: 'Japan',
  CH: 'Switzerland',
  AU: 'Australia',
  CA: 'Canada',
  FR: 'France',
  CN: 'China',
  TW: 'Taiwan',
  IN: 'India',
  KR: 'Korea',
  ES: 'Spain',
  SG: 'Singapore',
  SE: 'Sweden',
  HK: 'Hong Kong',
  NL: 'Netherlands',
  IT: 'Italy',
  BR: 'Brazil',
  DK: 'Denmark',
  ZA: 'South Africa',
  FI: 'Finland',
  MX: 'Mexico',
  MY: 'Malaysia',
  BE: 'Belgium',
  NO: 'Norway',
  AT: 'Austria',
  PL: 'Poland',
  US: 'USA',
  ID: 'Indonesia',
  TH: 'Thailand',
  IL: 'Israel',
  IE: 'Ireland',
  TR: 'Turkey',
  NZ: 'New Zealand',
  CL: 'Chile',
  PH: 'Philippines',
  PT: 'Portugal',
  GR: 'Greece',
  HU: 'Hungary',
  PE: 'Peru',
  CZ: 'Czech Republic',
  CO: 'Colombia',
  PK: 'Pakistan',
  SK: 'Slovakia',
  OTHER: 'Other',
};
