import type {TypographyVariantsOptions} from '@mui/material/styles';

const fontFamily = '"Roboto", "Helvetica", "Arial", sans-serif';

export const typography: TypographyVariantsOptions = {
  fontFamily,
  allVariants: {
    scrollMarginTop: 'calc(var(--MuiDocs-header-height) + 32px)',
  },
  htmlFontSize: 16,
  fontSize: 14,
  fontWeightLight: 300,
  fontWeightRegular: 400,
  fontWeightMedium: 500,
  fontWeightBold: 700,
  h1: {
    fontFamily,
    fontSize: 'clamp(2.625rem, 1.2857rem + 3.5714vw, 4rem)',
    fontWeight: 800,
    lineHeight: 1.1142857142857143,
    scrollMarginTop: 'calc(var(--MuiDocs-header-height) + 32px)',
  },
  h2: {
    fontFamily,
    fontSize: 'clamp(1.5rem, 0.9643rem + 1.4286vw, 2.25rem)',
    fontWeight: 800,
    lineHeight: 1.2222222222222223,
    color: '#E7EBF0',
    scrollMarginTop: 'calc(var(--MuiDocs-header-height) + 32px)',
  },
  h3: {
    fontFamily,
    fontSize: '2.25rem',
    lineHeight: 1.2222222222222223,
    letterSpacing: 0.2,
    fontWeight: 400,
    scrollMarginTop: 'calc(var(--MuiDocs-header-height) + 32px)',
  },
  h4: {
    fontFamily,
    fontSize: '1.75rem',
    lineHeight: 1.5,
    letterSpacing: 0.2,
    fontWeight: 400,
    scrollMarginTop: 'calc(var(--MuiDocs-header-height) + 32px)',
  },
  h5: {
    fontFamily,
    fontSize: '1.5rem',
    lineHeight: 1.5,
    letterSpacing: 0.1,
    fontWeight: 400,
    scrollMarginTop: 'calc(var(--MuiDocs-header-height) + 32px)',
  },
  h6: {
    fontSize: '1.25rem',
    lineHeight: 1.5,
    fontFamily,
    fontWeight: 500,
    scrollMarginTop: 'calc(var(--MuiDocs-header-height) + 32px)',
  },
  button: {
    textTransform: 'initial',
    fontWeight: 700,
    letterSpacing: 0,
    fontFamily,
    fontSize: '0.875rem',
    lineHeight: 1.75,
    scrollMarginTop: 'calc(var(--MuiDocs-header-height) + 32px)',
  },
  subtitle1: {
    fontSize: '1.125rem',
    lineHeight: 1.3333333333333333,
    letterSpacing: 0,
    fontWeight: 500,
    fontFamily,
    scrollMarginTop: 'calc(var(--MuiDocs-header-height) + 32px)',
  },
  body1: {
    fontSize: '1rem',
    lineHeight: 1.5,
    letterSpacing: 0,
    fontFamily,
    fontWeight: 400,
    scrollMarginTop: 'calc(var(--MuiDocs-header-height) + 32px)',
  },
  body2: {
    fontSize: '0.875rem',
    lineHeight: 1.5,
    letterSpacing: 0,
    fontFamily,
    fontWeight: 400,
    scrollMarginTop: 'calc(var(--MuiDocs-header-height) + 32px)',
  },
  caption: {
    display: 'inline-block',
    fontSize: '0.75rem',
    lineHeight: 1.5,
    letterSpacing: 0,
    fontWeight: 700,
    fontFamily,
    scrollMarginTop: 'calc(var(--MuiDocs-header-height) + 32px)',
  },
  subtitle2: {
    fontFamily,
    fontWeight: 500,
    fontSize: '0.875rem',
    lineHeight: 1.57,
    scrollMarginTop: 'calc(var(--MuiDocs-header-height) + 32px)',
  },
  overline: {
    fontFamily,
    fontWeight: 400,
    fontSize: '0.75rem',
    lineHeight: 2.66,
    textTransform: 'uppercase',
    scrollMarginTop: 'calc(var(--MuiDocs-header-height) + 32px)',
  },
};
