name: Run Tests
on:
  push:
    branches-ignore: [main, dev]
  pull_request:
    branches-ignore: [main, dev]
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        bun-version: [1.0.0, 1.1.1]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}
      - run: |
          bun install
          CI=false bun run test
